import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Check, Star, Zap, Shield, Building } from "lucide-react"

export default function PricingPage() {
  const plans = [
    {
      name: "FREE",
      price: "$0",
      period: "",
      description: "Basic access, export .txt only.",
      icon: Star,
      features: [
        "Basic prompt generation",
        "Export .txt format",
        "Community support",
        "5 modules access",
        "Basic 7D framework",
        "Standard quality score",
      ],
      limitations: ["No advanced modules", "Limited export formats", "Community support only"],
      popular: false,
      cta: "Start Free",
      highlight: false,
    },
    {
      name: "CREATOR",
      price: "$29",
      period: "/month",
      description: "Enhanced capabilities, export .txt and .md.",
      icon: Zap,
      features: [
        "Enhanced prompt generation",
        "Export .txt and .md formats",
        "Priority support",
        "25 modules access",
        "Advanced 7D framework",
        "Quality score ≥ 75",
        "Basic analytics dashboard",
        "Template library access",
      ],
      limitations: ["No PDF/JSON exports", "Limited API calls"],
      popular: true,
      cta: "Start Creating",
      highlight: true,
    },
    {
      name: "PRO",
      price: "$79",
      period: "/month",
      description: "Advanced features, export .txt, .md, .pdf, .json (AI Score ≥ 80).",
      icon: Shield,
      features: [
        "Advanced prompt generation",
        "All export formats (.txt, .md, .pdf, .json)",
        "AI Score ≥ 80 guarantee",
        "All 50 modules access",
        "Advanced analytics & insights",
        "API access (1000 calls/month)",
        "Custom templates",
        "Priority email support",
        "Workflow automation",
        "Team collaboration (up to 5 users)",
      ],
      limitations: ["No white-label options", "Standard SLA"],
      popular: false,
      cta: "Go Pro",
      highlight: false,
    },
    {
      name: "ENTERPRISE",
      price: "$199",
      period: "/month",
      description: "Full enterprise-grade features, export all formats + .zip bundles.",
      icon: Building,
      features: [
        "Enterprise-grade features",
        "All formats + .zip bundles",
        "Custom integrations & webhooks",
        "Unlimited modules & custom modules",
        "White-label options",
        "Dedicated account manager",
        "99.9% SLA guarantee",
        "Unlimited API calls",
        "Advanced security & compliance",
        "Custom training & onboarding",
        "Unlimited team members",
        "Custom deployment options",
      ],
      limitations: [],
      popular: false,
      cta: "Contact Sales",
      highlight: false,
    },
  ]

  const faqs = [
    {
      question: "Can I change plans anytime?",
      answer:
        "Yes, upgrades and downgrades take effect immediately. You'll be prorated for any plan changes during your billing cycle.",
    },
    {
      question: "What payment methods do you accept?",
      answer:
        "All major credit cards via Stripe. Secure and encrypted. Enterprise customers can also pay via wire transfer or ACH.",
    },
    {
      question: "Is there a free trial?",
      answer:
        "Yes. The Free plan includes basics with no time limit. Paid plans include a 14-day money-back guarantee.",
    },
    {
      question: "Can I cancel anytime?",
      answer:
        "Absolutely. You'll keep access until the end of your billing cycle. No cancellation fees or hidden charges.",
    },
    {
      question: "What's included in the AI Score guarantee?",
      answer:
        "Pro and Enterprise plans guarantee AI-generated outputs score ≥80 on our quality metrics. If not, we'll regenerate until it meets the threshold.",
    },
    {
      question: "Do you offer volume discounts?",
      answer:
        "Yes! Enterprise customers with large teams or high usage get custom pricing. Contact our sales team for a quote.",
    },
    {
      question: "What kind of support do you provide?",
      answer:
        "Free: Community forums. Creator/Pro: Priority email support. Enterprise: Dedicated account manager + phone support.",
    },
    {
      question: "Can I use PromptForge for commercial projects?",
      answer: "Yes! All paid plans include commercial usage rights. You own the outputs generated by our platform.",
    },
  ]

  const testimonials = [
    {
      quote: "PromptForge transformed our content workflow. What used to take weeks now takes hours.",
      author: "Sarah Chen",
      role: "Content Director",
      company: "TechFlow Inc",
    },
    {
      quote: "The 7D framework gave us consistency across all our AI outputs. Game changer for our agency.",
      author: "Marcus Rodriguez",
      role: "Creative Director",
      company: "Pixel & Code",
    },
    {
      quote: "ROI was immediate. Our prompt quality scores went from 60% to 85% overnight.",
      author: "Dr. Emily Watson",
      role: "AI Research Lead",
      company: "DataVision Labs",
    },
  ]

  const comparisonFeatures = [
    { feature: "Modules Access", free: "5", creator: "25", pro: "50", enterprise: "Unlimited + Custom" },
    {
      feature: "Export Formats",
      free: ".txt",
      creator: ".txt, .md",
      pro: "All formats",
      enterprise: "All + .zip bundles",
    },
    { feature: "AI Score Guarantee", free: "Standard", creator: "≥75", pro: "≥80", enterprise: "≥85" },
    { feature: "API Calls/Month", free: "0", creator: "100", pro: "1,000", enterprise: "Unlimited" },
    { feature: "Team Members", free: "1", creator: "1", pro: "5", enterprise: "Unlimited" },
    {
      feature: "Support Level",
      free: "Community",
      creator: "Email",
      pro: "Priority Email",
      enterprise: "Dedicated Manager",
    },
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-card">
      {/* Hero Section */}
      <section className="py-20 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl font-bold text-primary mb-6 font-mono neon-text">
            Choose Your <span className="text-accent">Plan</span>
          </h1>
          <p className="text-xl text-muted-foreground font-mono max-w-3xl mx-auto mb-8">
            Unlock the full power of prompt engineering with flexible plans. Start free, scale as you grow.
          </p>
          <div className="flex items-center justify-center gap-4 text-sm font-mono">
            <Badge variant="outline" className="border-primary/50 text-primary">
              14-day money-back guarantee
            </Badge>
            <Badge variant="outline" className="border-primary/50 text-primary">
              No setup fees
            </Badge>
            <Badge variant="outline" className="border-primary/50 text-primary">
              Cancel anytime
            </Badge>
          </div>
        </div>
      </section>

      {/* Pricing Cards */}
      <section className="py-20 px-6 bg-card/20">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-20">
            {plans.map((plan) => {
              const IconComponent = plan.icon
              return (
                <Card
                  key={plan.name}
                  className={`relative bg-card/50 backdrop-blur-sm border-border hover:border-primary/50 transition-all duration-300 hover:shadow-lg hover:shadow-primary/20 ${
                    plan.highlight ? "ring-2 ring-primary/50 border-primary/50" : ""
                  }`}
                >
                  {plan.popular && (
                    <Badge className="absolute -top-3 left-1/2 transform -translate-x-1/2 bg-primary text-primary-foreground font-mono">
                      Most Popular
                    </Badge>
                  )}

                  <CardHeader className="text-center pb-4">
                    <div className="flex items-center justify-center mb-4">
                      <div className="p-3 bg-primary/10 rounded-full">
                        <IconComponent className="w-8 h-8 text-primary" />
                      </div>
                    </div>
                    <CardTitle className="text-2xl font-bold text-foreground mb-2 font-mono">{plan.name}</CardTitle>
                    <div className="text-4xl font-bold text-primary mb-2 font-mono">
                      {plan.price}
                      {plan.period && <span className="text-lg text-muted-foreground">{plan.period}</span>}
                    </div>
                    <CardDescription className="text-muted-foreground text-sm font-mono">
                      {plan.description}
                    </CardDescription>
                  </CardHeader>

                  <CardContent className="space-y-6">
                    <ul className="space-y-3">
                      {plan.features.map((feature, index) => (
                        <li key={index} className="flex items-start text-muted-foreground">
                          <Check className="w-4 h-4 text-primary mr-3 flex-shrink-0 mt-0.5" />
                          <span className="font-mono text-sm">{feature}</span>
                        </li>
                      ))}
                    </ul>

                    <Button
                      className={`w-full font-mono ${
                        plan.highlight
                          ? "bg-primary hover:bg-primary/90 text-primary-foreground"
                          : "bg-card hover:bg-muted text-foreground border border-border"
                      }`}
                    >
                      {plan.cta}
                    </Button>
                  </CardContent>
                </Card>
              )
            })}
          </div>
        </div>
      </section>

      {/* Feature Comparison Table */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-4xl font-bold text-primary mb-12 text-center font-mono neon-text">Feature Comparison</h2>
          <Card className="bg-card/50 backdrop-blur-sm border-border overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border">
                    <th className="text-left p-4 font-mono text-muted-foreground">Feature</th>
                    <th className="text-center p-4 font-mono text-foreground">Free</th>
                    <th className="text-center p-4 font-mono text-foreground">Creator</th>
                    <th className="text-center p-4 font-mono text-foreground">Pro</th>
                    <th className="text-center p-4 font-mono text-foreground">Enterprise</th>
                  </tr>
                </thead>
                <tbody>
                  {comparisonFeatures.map((row, index) => (
                    <tr key={index} className="border-b border-border/50 hover:bg-muted/20">
                      <td className="p-4 font-mono text-foreground font-medium">{row.feature}</td>
                      <td className="p-4 text-center font-mono text-muted-foreground">{row.free}</td>
                      <td className="p-4 text-center font-mono text-muted-foreground">{row.creator}</td>
                      <td className="p-4 text-center font-mono text-muted-foreground">{row.pro}</td>
                      <td className="p-4 text-center font-mono text-muted-foreground">{row.enterprise}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 px-6 bg-card/20">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-4xl font-bold text-primary mb-12 text-center font-mono neon-text">What Our Users Say</h2>
          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <Card
                key={index}
                className="bg-card/50 backdrop-blur-sm border-border hover:border-primary/50 transition-all duration-300"
              >
                <CardContent className="p-6">
                  <p className="text-muted-foreground font-mono text-sm leading-relaxed mb-4 italic">
                    "{testimonial.quote}"
                  </p>
                  <div className="border-t border-border pt-4">
                    <p className="text-foreground font-mono font-medium">{testimonial.author}</p>
                    <p className="text-muted-foreground font-mono text-xs">{testimonial.role}</p>
                    <p className="text-accent font-mono text-xs">{testimonial.company}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold text-primary mb-12 text-center font-mono neon-text">
            Frequently Asked Questions
          </h2>
          <div className="grid md:grid-cols-2 gap-8">
            {faqs.map((faq, index) => (
              <Card
                key={index}
                className="bg-card/50 backdrop-blur-sm border-border hover:border-primary/50 transition-all duration-300"
              >
                <CardContent className="p-6">
                  <h3 className="text-lg font-bold text-accent mb-3 font-mono">{faq.question}</h3>
                  <p className="text-muted-foreground font-mono text-sm leading-relaxed">{faq.answer}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-6 bg-card/20">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-bold text-primary mb-6 font-mono neon-text text-balance">
            Ready to Transform Your Prompts?
          </h2>
          <p className="text-xl text-muted-foreground font-mono mb-8">
            Join thousands of professionals who've upgraded their AI workflow with PromptForge™.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button
              size="lg"
              className="bg-primary hover:bg-primary/90 text-primary-foreground font-mono text-lg px-8 py-4"
            >
              Start Free Trial
            </Button>
            <Button
              variant="outline"
              size="lg"
              className="border-primary/50 text-primary hover:bg-primary/10 font-mono text-lg px-8 py-4 bg-transparent"
            >
              Schedule Demo
            </Button>
          </div>
          <p className="text-sm text-muted-foreground font-mono mt-4">
            No credit card required • 14-day money-back guarantee
          </p>
        </div>
      </section>
    </div>
  )
}
