import { z } from 'zod'

export const ModuleSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  category: z.enum(['content', 'analysis', 'optimization', 'integration']),
  difficulty: z.enum(['beginner', 'intermediate', 'advanced']),
  tags: z.array(z.string()),
  prompt: z.string(),
  parameters: z.record(z.any()),
  examples: z.array(z.object({
    input: z.string(),
    output: z.string(),
  })),
})

export type Module = z.infer<typeof ModuleSchema>

export const MODULES: Module[] = [
  {
    id: 'M01',
    name: 'Content Generator',
    description: 'Generate high-quality content for any topic',
    category: 'content',
    difficulty: 'beginner',
    tags: ['content', 'writing', 'generation'],
    prompt: 'Generate comprehensive content about {topic} with the following requirements: {requirements}',
    parameters: {
      topic: 'string',
      requirements: 'string',
      tone: 'string',
      length: 'string',
    },
    examples: [
      {
        input: 'Topic: AI, Requirements: Technical but accessible, Tone: Professional, Length: 500 words',
        output: 'Artificial Intelligence (AI) represents one of the most transformative technologies of our time...'
      }
    ]
  },
  {
    id: 'M02',
    name: 'Text Analyzer',
    description: 'Analyze text for sentiment, keywords, and structure',
    category: 'analysis',
    difficulty: 'intermediate',
    tags: ['analysis', 'sentiment', 'keywords'],
    prompt: 'Analyze the following text: {text}. Provide sentiment analysis, key themes, and structural insights.',
    parameters: {
      text: 'string',
      analysis_type: 'string',
    },
    examples: [
      {
        input: 'Text: "This product is amazing! I love it so much."',
        output: 'Sentiment: Positive (0.8), Key themes: Product satisfaction, emotional attachment'
      }
    ]
  },
  {
    id: 'M03',
    name: 'Prompt Optimizer',
    description: 'Optimize prompts for better AI responses',
    category: 'optimization',
    difficulty: 'advanced',
    tags: ['optimization', 'prompting', 'efficiency'],
    prompt: 'Optimize this prompt for better AI performance: {original_prompt}. Consider clarity, specificity, and context.',
    parameters: {
      original_prompt: 'string',
      optimization_goals: 'array',
    },
    examples: [
      {
        input: 'Original: "Write about cats"',
        output: 'Optimized: "Write a comprehensive 300-word article about domestic cats, focusing on their behavior, care requirements, and benefits as pets. Use a friendly, informative tone suitable for pet owners."'
      }
    ]
  },
  // Add more modules as needed
]

export function getModuleById(id: string): Module | undefined {
  return MODULES.find(module => module.id === id)
}

export function getModulesByCategory(category: string): Module[] {
  return MODULES.filter(module => module.category === category)
}

export function searchModules(query: string): Module[] {
  const lowercaseQuery = query.toLowerCase()
  return MODULES.filter(module => 
    module.name.toLowerCase().includes(lowercaseQuery) ||
    module.description.toLowerCase().includes(lowercaseQuery) ||
    module.tags.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  )
}

// Extended module schema for API compatibility
export const ExtendedModuleSchema = z.object({
  id: z.string(),
  title: z.string(),
  slug: z.string(),
  summary: z.string(),
  vectors: z.array(z.string()),
  difficulty: z.number(),
  minPlan: z.string(),
  tags: z.array(z.string()),
  outputs: z.array(z.string()),
  version: z.string(),
  deprecated: z.boolean().optional(),
})

export type ExtendedModule = z.infer<typeof ExtendedModuleSchema>

// Full catalog of 50 modules for the 7-D framework
export const catalogData = {
  version: "1.0.0",
  modules: {
    'M01': {
      id: 'M01',
      title: 'Strategic Framework Generator',
      slug: 'strategic-framework-generator',
      summary: 'Generate comprehensive strategic frameworks for business planning and execution',
      vectors: ['strategic', 'analytics'],
      difficulty: 2,
      minPlan: 'FREE',
      tags: ['strategy', 'business', 'planning'],
      outputs: ['text', 'markdown'],
      version: '1.0.0',
      deprecated: false,
    },
    'M02': {
      id: 'M02',
      title: 'Content Strategy Builder',
      slug: 'content-strategy-builder',
      summary: 'Create data-driven content strategies with performance metrics and audience insights',
      vectors: ['content', 'analytics', 'branding'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['content', 'strategy', 'marketing'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M03': {
      id: 'M03',
      title: 'Crisis Communication Framework',
      slug: 'crisis-communication-framework',
      summary: 'Develop rapid response communication strategies for crisis management scenarios',
      vectors: ['crisis', 'rhetoric', 'strategic'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['crisis', 'communication', 'management'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M04': {
      id: 'M04',
      title: 'Brand Voice Analyzer',
      slug: 'brand-voice-analyzer',
      summary: 'Analyze and optimize brand voice consistency across all communication channels',
      vectors: ['branding', 'content', 'analytics'],
      difficulty: 2,
      minPlan: 'CREATOR',
      tags: ['branding', 'voice', 'analysis'],
      outputs: ['text', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M05': {
      id: 'M05',
      title: 'Cognitive Bias Detector',
      slug: 'cognitive-bias-detector',
      summary: 'Identify and mitigate cognitive biases in decision-making processes',
      vectors: ['cognitive', 'analytics', 'strategic'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['cognitive', 'bias', 'decision-making'],
      outputs: ['text', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M06': {
      id: 'M06',
      title: 'Rhetorical Analysis Engine',
      slug: 'rhetorical-analysis-engine',
      summary: 'Analyze persuasive techniques and rhetorical effectiveness in communication',
      vectors: ['rhetoric', 'analytics', 'content'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['rhetoric', 'persuasion', 'analysis'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M07': {
      id: 'M07',
      title: 'Data Storytelling Framework',
      slug: 'data-storytelling-framework',
      summary: 'Transform complex data into compelling narratives for stakeholder engagement',
      vectors: ['analytics', 'content', 'strategic'],
      difficulty: 3,
      minPlan: 'PRO',
      tags: ['data', 'storytelling', 'narrative'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M08': {
      id: 'M08',
      title: 'Stakeholder Mapping Tool',
      slug: 'stakeholder-mapping-tool',
      summary: 'Create comprehensive stakeholder maps for project and change management',
      vectors: ['strategic', 'analytics', 'cognitive'],
      difficulty: 2,
      minPlan: 'CREATOR',
      tags: ['stakeholder', 'mapping', 'management'],
      outputs: ['text', 'markdown'],
      version: '1.0.0',
      deprecated: false,
    },
    'M09': {
      id: 'M09',
      title: 'Change Management Protocol',
      slug: 'change-management-protocol',
      summary: 'Develop structured approaches for managing organizational change and transformation',
      vectors: ['strategic', 'cognitive', 'crisis'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['change', 'management', 'transformation'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M10': {
      id: 'M10',
      title: 'Content Performance Optimizer',
      slug: 'content-performance-optimizer',
      summary: 'Optimize content performance through data-driven insights and A/B testing',
      vectors: ['content', 'analytics', 'branding'],
      difficulty: 3,
      minPlan: 'FREE',
      tags: ['content', 'optimization', 'performance'],
      outputs: ['text', 'markdown'],
      version: '1.0.0',
      deprecated: false,
    },
    'M11': {
      id: 'M11',
      title: 'Risk Assessment Framework',
      slug: 'risk-assessment-framework',
      summary: 'Systematic approach to identifying, analyzing, and mitigating business risks',
      vectors: ['strategic', 'analytics', 'crisis'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['risk', 'assessment', 'management'],
      outputs: ['text', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M12': {
      id: 'M12',
      title: 'Audience Persona Builder',
      slug: 'audience-persona-builder',
      summary: 'Create detailed audience personas for targeted marketing and communication',
      vectors: ['branding', 'analytics', 'content'],
      difficulty: 2,
      minPlan: 'CREATOR',
      tags: ['audience', 'persona', 'marketing'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M13': {
      id: 'M13',
      title: 'Competitive Analysis Engine',
      slug: 'competitive-analysis-engine',
      summary: 'Comprehensive competitive analysis framework for market positioning',
      vectors: ['strategic', 'analytics', 'branding'],
      difficulty: 3,
      minPlan: 'PRO',
      tags: ['competitive', 'analysis', 'positioning'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M14': {
      id: 'M14',
      title: 'Message Architecture Designer',
      slug: 'message-architecture-designer',
      summary: 'Design hierarchical message architectures for consistent brand communication',
      vectors: ['branding', 'content', 'strategic'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['message', 'architecture', 'branding'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M15': {
      id: 'M15',
      title: 'Ethical AI Guidelines',
      slug: 'ethical-ai-guidelines',
      summary: 'Develop comprehensive guidelines for ethical AI development and deployment',
      vectors: ['cognitive', 'strategic', 'crisis'],
      difficulty: 5,
      minPlan: 'ENTERPRISE',
      tags: ['ethics', 'AI', 'guidelines'],
      outputs: ['text', 'markdown', 'json', 'pdf', 'zip'],
      version: '1.0.0',
      deprecated: false,
    },
    'M16': {
      id: 'M16',
      title: 'Innovation Pipeline Manager',
      slug: 'innovation-pipeline-manager',
      summary: 'Manage innovation pipelines from ideation to market implementation',
      vectors: ['strategic', 'cognitive', 'analytics'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['innovation', 'pipeline', 'management'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M17': {
      id: 'M17',
      title: 'Digital Transformation Roadmap',
      slug: 'digital-transformation-roadmap',
      summary: 'Create comprehensive roadmaps for digital transformation initiatives',
      vectors: ['strategic', 'analytics', 'crisis'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['digital', 'transformation', 'roadmap'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M18': {
      id: 'M18',
      title: 'Content Calendar Generator',
      slug: 'content-calendar-generator',
      summary: 'Generate strategic content calendars aligned with business objectives',
      vectors: ['content', 'strategic', 'branding'],
      difficulty: 1,
      minPlan: 'FREE',
      tags: ['content', 'calendar', 'planning'],
      outputs: ['text', 'markdown'],
      version: '1.0.0',
      deprecated: false,
    },
    'M19': {
      id: 'M19',
      title: 'Brand Guidelines Creator',
      slug: 'brand-guidelines-creator',
      summary: 'Develop comprehensive brand guidelines for consistent visual and verbal identity',
      vectors: ['branding', 'content', 'strategic'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['brand', 'guidelines', 'identity'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M20': {
      id: 'M20',
      title: 'Crisis Response Playbook',
      slug: 'crisis-response-playbook',
      summary: 'Create detailed crisis response playbooks for various emergency scenarios',
      vectors: ['crisis', 'strategic', 'rhetoric'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['crisis', 'response', 'playbook'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M21': {
      id: 'M21',
      title: 'Market Research Framework',
      slug: 'market-research-framework',
      summary: 'Comprehensive framework for conducting market research and analysis',
      vectors: ['analytics', 'strategic', 'cognitive'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['market', 'research', 'analysis'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M22': {
      id: 'M22',
      title: 'Thought Leadership Strategy',
      slug: 'thought-leadership-strategy',
      summary: 'Develop thought leadership strategies for industry positioning and influence',
      vectors: ['strategic', 'content', 'branding'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['thought', 'leadership', 'strategy'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M23': {
      id: 'M23',
      title: 'Customer Journey Mapper',
      slug: 'customer-journey-mapper',
      summary: 'Map comprehensive customer journeys for improved experience design',
      vectors: ['branding', 'analytics', 'strategic'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['customer', 'journey', 'experience'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M24': {
      id: 'M24',
      title: 'Performance Metrics Dashboard',
      slug: 'performance-metrics-dashboard',
      summary: 'Design performance metrics dashboards for business intelligence',
      vectors: ['analytics', 'strategic', 'cognitive'],
      difficulty: 3,
      minPlan: 'PRO',
      tags: ['performance', 'metrics', 'dashboard'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M25': {
      id: 'M25',
      title: 'Communication Audit Tool',
      slug: 'communication-audit-tool',
      summary: 'Comprehensive audit tool for organizational communication effectiveness',
      vectors: ['content', 'analytics', 'branding'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['communication', 'audit', 'effectiveness'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M26': {
      id: 'M26',
      title: 'Strategic Planning Workshop',
      slug: 'strategic-planning-workshop',
      summary: 'Design strategic planning workshops for organizational alignment',
      vectors: ['strategic', 'cognitive', 'crisis'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['strategic', 'planning', 'workshop'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M27': {
      id: 'M27',
      title: 'Brand Positioning Statement',
      slug: 'brand-positioning-statement',
      summary: 'Create compelling brand positioning statements for market differentiation',
      vectors: ['branding', 'strategic', 'rhetoric'],
      difficulty: 2,
      minPlan: 'CREATOR',
      tags: ['brand', 'positioning', 'differentiation'],
      outputs: ['text', 'markdown'],
      version: '1.0.0',
      deprecated: false,
    },
    'M28': {
      id: 'M28',
      title: 'Crisis Communication Training',
      slug: 'crisis-communication-training',
      summary: 'Develop crisis communication training programs for teams',
      vectors: ['crisis', 'rhetoric', 'content'],
      difficulty: 3,
      minPlan: 'PRO',
      tags: ['crisis', 'training', 'communication'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M29': {
      id: 'M29',
      title: 'Data Privacy Framework',
      slug: 'data-privacy-framework',
      summary: 'Comprehensive framework for data privacy and protection compliance',
      vectors: ['cognitive', 'strategic', 'crisis'],
      difficulty: 4,
      minPlan: 'ENTERPRISE',
      tags: ['privacy', 'data', 'compliance'],
      outputs: ['text', 'markdown', 'json', 'pdf', 'zip'],
      version: '1.0.0',
      deprecated: false,
    },
    'M30': {
      id: 'M30',
      title: 'Content Governance Policy',
      slug: 'content-governance-policy',
      summary: 'Develop content governance policies for brand consistency',
      vectors: ['content', 'strategic', 'branding'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['content', 'governance', 'policy'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M31': {
      id: 'M31',
      title: 'Innovation Strategy Framework',
      slug: 'innovation-strategy-framework',
      summary: 'Strategic framework for driving innovation and creativity',
      vectors: ['strategic', 'cognitive', 'analytics'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['innovation', 'strategy', 'creativity'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M32': {
      id: 'M32',
      title: 'Brand Voice Guidelines',
      slug: 'brand-voice-guidelines',
      summary: 'Create comprehensive brand voice guidelines for consistent communication',
      vectors: ['branding', 'content', 'rhetoric'],
      difficulty: 2,
      minPlan: 'CREATOR',
      tags: ['brand', 'voice', 'guidelines'],
      outputs: ['text', 'markdown'],
      version: '1.0.0',
      deprecated: false,
    },
    'M33': {
      id: 'M33',
      title: 'Crisis Simulation Scenarios',
      slug: 'crisis-simulation-scenarios',
      summary: 'Develop crisis simulation scenarios for team preparedness',
      vectors: ['crisis', 'strategic', 'cognitive'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['crisis', 'simulation', 'preparedness'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M34': {
      id: 'M34',
      title: 'Market Entry Strategy',
      slug: 'market-entry-strategy',
      summary: 'Comprehensive market entry strategies for new markets',
      vectors: ['strategic', 'analytics', 'crisis'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['market', 'entry', 'strategy'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M35': {
      id: 'M35',
      title: 'Content Performance Analytics',
      slug: 'content-performance-analytics',
      summary: 'Advanced analytics framework for content performance measurement',
      vectors: ['analytics', 'content', 'strategic'],
      difficulty: 3,
      minPlan: 'PRO',
      tags: ['content', 'analytics', 'performance'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M36': {
      id: 'M36',
      title: 'Brand Architecture Designer',
      slug: 'brand-architecture-designer',
      summary: 'Design comprehensive brand architectures for complex organizations',
      vectors: ['branding', 'strategic', 'cognitive'],
      difficulty: 4,
      minPlan: 'ENTERPRISE',
      tags: ['brand', 'architecture', 'design'],
      outputs: ['text', 'markdown', 'json', 'pdf', 'zip'],
      version: '1.0.0',
      deprecated: false,
    },
    'M37': {
      id: 'M37',
      title: 'Crisis Recovery Framework',
      slug: 'crisis-recovery-framework',
      summary: 'Systematic approach to crisis recovery and business continuity',
      vectors: ['crisis', 'strategic', 'analytics'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['crisis', 'recovery', 'continuity'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M38': {
      id: 'M38',
      title: 'Strategic Communication Plan',
      slug: 'strategic-communication-plan',
      summary: 'Develop comprehensive strategic communication plans',
      vectors: ['strategic', 'content', 'rhetoric'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['strategic', 'communication', 'planning'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M39': {
      id: 'M39',
      title: 'Brand Equity Measurement',
      slug: 'brand-equity-measurement',
      summary: 'Framework for measuring and tracking brand equity over time',
      vectors: ['branding', 'analytics', 'strategic'],
      difficulty: 3,
      minPlan: 'PRO',
      tags: ['brand', 'equity', 'measurement'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M40': {
      id: 'M40',
      title: 'Cognitive Load Optimizer',
      slug: 'cognitive-load-optimizer',
      summary: 'Optimize cognitive load in communication and user experience',
      vectors: ['cognitive', 'content', 'analytics'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['cognitive', 'load', 'optimization'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M41': {
      id: 'M41',
      title: 'Rhetorical Device Analyzer',
      slug: 'rhetorical-device-analyzer',
      summary: 'Analyze and optimize rhetorical devices in communication',
      vectors: ['rhetoric', 'content', 'analytics'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['rhetoric', 'devices', 'analysis'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M42': {
      id: 'M42',
      title: 'Strategic Narrative Builder',
      slug: 'strategic-narrative-builder',
      summary: 'Build compelling strategic narratives for organizational change',
      vectors: ['strategic', 'content', 'rhetoric'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['strategic', 'narrative', 'change'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M43': {
      id: 'M43',
      title: 'Brand Experience Designer',
      slug: 'brand-experience-designer',
      summary: 'Design comprehensive brand experiences across all touchpoints',
      vectors: ['branding', 'cognitive', 'strategic'],
      difficulty: 4,
      minPlan: 'ENTERPRISE',
      tags: ['brand', 'experience', 'design'],
      outputs: ['text', 'markdown', 'json', 'pdf', 'zip'],
      version: '1.0.0',
      deprecated: false,
    },
    'M44': {
      id: 'M44',
      title: 'Crisis Communication Metrics',
      slug: 'crisis-communication-metrics',
      summary: 'Framework for measuring crisis communication effectiveness',
      vectors: ['crisis', 'analytics', 'strategic'],
      difficulty: 3,
      minPlan: 'PRO',
      tags: ['crisis', 'metrics', 'effectiveness'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M45': {
      id: 'M45',
      title: 'Content Strategy Framework',
      slug: 'content-strategy-framework',
      summary: 'Comprehensive framework for content strategy development',
      vectors: ['content', 'strategic', 'branding'],
      difficulty: 3,
      minPlan: 'CREATOR',
      tags: ['content', 'strategy', 'framework'],
      outputs: ['text', 'markdown', 'json'],
      version: '1.0.0',
      deprecated: false,
    },
    'M46': {
      id: 'M46',
      title: 'Strategic Decision Framework',
      slug: 'strategic-decision-framework',
      summary: 'Framework for making strategic decisions under uncertainty',
      vectors: ['strategic', 'cognitive', 'analytics'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['strategic', 'decision', 'framework'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M47': {
      id: 'M47',
      title: 'Brand Consistency Monitor',
      slug: 'brand-consistency-monitor',
      summary: 'Monitor and maintain brand consistency across all channels',
      vectors: ['branding', 'analytics', 'content'],
      difficulty: 2,
      minPlan: 'CREATOR',
      tags: ['brand', 'consistency', 'monitoring'],
      outputs: ['text', 'markdown'],
      version: '1.0.0',
      deprecated: false,
    },
    'M48': {
      id: 'M48',
      title: 'Crisis Prevention Protocol',
      slug: 'crisis-prevention-protocol',
      summary: 'Develop protocols for preventing and mitigating potential crises',
      vectors: ['crisis', 'strategic', 'cognitive'],
      difficulty: 4,
      minPlan: 'PRO',
      tags: ['crisis', 'prevention', 'protocol'],
      outputs: ['text', 'markdown', 'json', 'pdf'],
      version: '1.0.0',
      deprecated: false,
    },
    'M49': {
      id: 'M49',
      title: 'Strategic Communication Audit',
      slug: 'strategic-communication-audit',
      summary: 'Comprehensive audit of strategic communication effectiveness',
      vectors: ['strategic', 'analytics', 'content'],
      difficulty: 4,
      minPlan: 'ENTERPRISE',
      tags: ['strategic', 'communication', 'audit'],
      outputs: ['text', 'markdown', 'json', 'pdf', 'zip'],
      version: '1.0.0',
      deprecated: false,
    },
    'M50': {
      id: 'M50',
      title: 'Brand Transformation Roadmap',
      slug: 'brand-transformation-roadmap',
      summary: 'Create comprehensive roadmaps for brand transformation initiatives',
      vectors: ['branding', 'strategic', 'crisis'],
      difficulty: 5,
      minPlan: 'ENTERPRISE',
      tags: ['brand', 'transformation', 'roadmap'],
      outputs: ['text', 'markdown', 'json', 'pdf', 'zip'],
      version: '1.0.0',
      deprecated: false,
    }
  }
}

export function validateModuleCatalog(catalog: any) {
  return {
    version: catalog.version,
    modules: catalog.modules
  }
}
