-- 0023_seed_full_catalog.sql — seed complet pentru catalogul M01-M50
begin;

-- Seed pentru toate modulele din catalog
insert into modules (id, title, description) values
  ('M01', 'AI‑IDEI.SOPFORGE™', 'Persona & Offer Clarifier — definești avatar, problemă, promisiune, ofertă'),
  ('M02', 'AI‑IDEI.LATENTMAP™', 'Message‑Market Fit Map — mapezi mesaje pe segmente & canale cu dovezi'),
  ('M03', 'Codul 7:1™', 'Narrative Positioning — poveste de poziționare (brand spine)'),
  ('M04', 'Dicționarul Semiotic 8VULTUS™', 'Value Ladder & Bundles — pachete, upsell/cross‑sell, margini'),
  ('M05', 'ORAKON Memory Grid', 'Funnel Blueprint — arhitectură TOFU‑MOFU‑BOFU + KPI'),
  ('M06', 'Agentic GPT Sales (Hunter/Closer)', 'Objection Mining — obiecții + contra‑argumente clasate'),
  ('M07', 'Risk & Trust Reversal', 'Risk & Trust Reversal — garanții + dovadă → scazi drop‑off'),
  ('M08', 'Status‑Tier Loyalty', 'Social Proof Matrix — testimoniale, studii, validări sistematizate'),
  ('M09', 'Post‑Purchase Subscription Engine', 'Pricing Strategy — ancore, planuri, discounting controlat, A/B'),
  ('M10', 'Zero‑Party Data OS', 'Offer Terms & SLA — clauze, SLA, rampe de risc, conformitate'),
  ('M11', 'Funnel Nota Doi', 'Content Strategy OS — piloni, calendar, repurpose, distribuție'),
  ('M12', 'Diagnostic Vizibilitate (8 piloni)', 'SEO/Intent Playbook — hărți intenție → conținut, briefuri, structuri'),
  ('M13', 'Pricing Psychology', 'Ads Creative Generator — concepte, copys, hooks, variații'),
  ('M14', 'Authority Content→Commerce', 'Landing Page Spec — structură, blocuri, micro‑conversii'),
  ('M15', 'GTD de Lançare Ritualică', 'Email Lifecycle — onboarding, nurture, winback cu KPI'),
  ('M16', 'HeyGen AI Clone', 'Sales Scripts (JTBD) — scenarii pe situații, closing paths'),
  ('M17', 'Sora Shot-by-Shot', 'Demo/Deck Architect — storyboard + slide spec convingător'),
  ('M18', 'Carusele RFA', 'Retention & LTV — anti‑churn, expansion, NRR playbook'),
  ('M19', 'Rescriere după algoritm', 'Referral & Ambassador — program parteneri, stimulente, KPI'),
  ('M20', 'Manifest Voice', 'Community Engine — membership, ritualuri, moderare'),
  ('M21', 'AI în Moodle', 'SOP Builder — procese operaționale + checklisturi auditabile'),
  ('M22', 'Lead Gen SOP (Make + Notion + Telegram)', 'QA & Test Harness — plan de test, criterii, rapoarte, gates'),
  ('M23', 'Podcast → Carte', 'Support & Success OS — macro‑procese CS, macros, KB'),
  ('M24', 'PR Personal', 'Incident & Crisis Comms — criză, status page, mesaje'),
  ('M25', 'Knowledge Security SOP', 'Compliance Pack — mapezi norme (GDPR/ISO/PCI) → controale'),
  ('M26', 'JTBD Matrix', 'Data & Metrics Spec — definiții, surse, dashboards, fiabilitate'),
  ('M27', 'Schwartz Ladder', 'Experimentation Lab — ipoteze, design test, MDE, analiză'),
  ('M28', 'Obiecții → Contraargumente', 'Partner & Affiliate — parteneri, termeni, tracking'),
  ('M29', 'Indoctrinare Soft', 'Product Research Agent — colectează/rezumă dovezi'),
  ('M30', 'Cod Anti-Conformism', 'ICP/Segmentation — segmentare + mesaje'),
  ('M31', 'Closed‑Loop Telemetry', 'Brand Voice Codex — stil, ritm, lexicon, interdicții, exemple'),
  ('M32', 'Cohort Experiments', 'Visual Identity Brief — cerințe vizuale, sistem, livrabile'),
  ('M33', 'Lead Scoring Model', 'Webinar/Workshop Kit — structură, flow, CTA, execuție'),
  ('M34', 'K‑Factors & bucle de recomandare', 'Crisis Risk Map — riscuri, probabilitate × impact, plan'),
  ('M35', 'Content Heatmap', 'GTM Planner — lansare: canale, bugete, milestones'),
  ('M36', 'Semiotic Brand Architecture', 'Enterprise RFP Responder — răspunsuri structurate la RFP'),
  ('M37', 'Ritual de Inițiere pentru The Architect', 'Procurement Readiness — pachet legal, securitate, DS, politici'),
  ('M38', 'Blueprint Antișcoală', 'Knowledge Base Writer — articole, structuri, taxonomii'),
  ('M39', 'Promptoscopie™', 'Training Curriculum — plan pe module, rezultate, evaluări'),
  ('M40', 'Voice System KPI', 'Hiring Scorecards — roluri, criterii, interviuri, decizii'),
  ('M41', 'Agent de Criză PR', 'OKR Designer — obiective, key results, aliniere'),
  ('M42', 'Contra‑cadru mediatic', 'Roadmapping OS — hartă trimestrială/anuală, dependențe'),
  ('M43', 'Politica de Transparență', 'Budget & Unit Economics — P&L, CAC/LTV, payback'),
  ('M44', 'Ethical Guardrails GPT', 'Localization & Intl — piețe, adaptări, conformități locale'),
  ('M45', 'Simulator de Contrafactuale', 'Accessibility & A11y — WCAG, testare, remedieri'),
  ('M46', 'Librărie Swipe Files', 'Security Controls Spec — controale, politici, audit trail'),
  ('M47', 'Curriculum INTELIGENȚIA™ (5 săpt.)', 'Data Privacy Pack — registre, DSR, rețineri, DPIA'),
  ('M48', 'Playbook Internaționalizare (EN/RO)', 'API & Integration Spec — endpointuri, SLA, versionare'),
  ('M49', 'Assistant GPT pentru Nota Doi', 'Telemetry & Observability — loguri, dashboards, alerte'),
  ('M50', 'Sistemul CUSNIR.OS™', 'Bundle Export Designer — layout md/json/pdf, watermark, checksum')
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description;

commit;
